### ISSUE TITLE
CoreScore 2.0 meta issue

### ISSUE THREAD

**Issue by olofk** [olofk/corescore#58]
A meta issue to collect all the things we want to implement for CoreScore 2.0
* [ ] A ring bus to replace the mux
* [ ] Move memory out from corescorecore to easier allow several instances to share one memory
* [ ] Use a newer version of SERV
